### ISSUE TITLE
Smelter Issue

### ISSUE THREAD

**Issue by Brobaseidon** [Awbugl/ProjectGenesis#11]
I think it is with this mod at least, sorry if it isn't. When I unlock the Circuit Etching Technology, it replaces the MK1 Smelter Recipe with the MK2 smelter recipe. The MK2 Smelter still needs the MK1 to be made, but this issue makes it so that the MK1 can no longer be made, as the recipe for it only opens to the MK2 smelter recipe. 
![image](https://user-images.githubusercontent.com/119133069/204106251-f2da3add-5bbb-4f42-947c-0f632983052b.png)

**Comment by Awbugl** [comment]
It looks like you are using the `BetterMachines` mod too, which is in conflict with `GenesisBook`. 

I presume this problem is due to the tech ID added by the two mods overlap, or `BetterMachines` modifies the location of the MK2 Smelter, overwriting the location of MK1.

We currently have no solutions for resolving conflicts—because DSP recipes, items, and techs use numeric IDs. The location of are numbers too. 

I personally recommend not opening conflicting mods at the same time (by the way, `MoreMegaStructure` / `TheyComeFromVoid` also have conflicts with `GenesisBook`). 

Thank you for your feedback!

**Comment by Brobaseidon** [comment]
Thanks for the reply! Didn't realize that was the issue as there was no error message like with TheyComeFromVoid and MoreMegaStructures.
