### ISSUE TITLE
Extremely Inaccessible Interplanetary Logistics

### ISSUE THREAD

**Issue by GabrielBallardin** [Awbugl/ProjectGenesis#19]
I believe that the interplanetary tower with large ships needs to be balanced, there is no way to continue playing with only 2 towers initially provided, the need for quantum chips in this tower is surreal for an early stage of the game, since the orange microchip is already extremely complex in terms of if you do. please make interplanetary logistics more accessible.

**Comment by Awbugl** [comment]
Hi, thanks for playing our mod. the signal of early stage ended in the mod is a stable production line for the processor - even 10/min is enough. 

two ILS are perfectly sufficient for the early stage - because we drastically reduced the difficulty of manufacturing the matrix.

ILS is not a product of early stage in our mod, the stable establishment of logistics transport belongs to the mid-stage content of the mod now.

and thank you again for playing our mod!

**Comment by Awbugl** [comment]
my friend did you unlocked Ocean Outfall tech?
it is designed for by-products.
and again ILS is not a early stage product in our mod.
