### ISSUE TITLE
Unbalance of Solar Candles

### ISSUE THREAD

**Issue by GabrielBallardin** [Awbugl/ProjectGenesis#22]
![image](https://user-images.githubusercontent.com/58851234/218153681-fe2c89f6-53cf-4a77-b089-41f0e7ae2b63.png)

Friend, I'm playing every step of your mod, and I'm coming across some things that don't make much sense.

If you can reflect with affection, thank you, or at least explain what your idea really is with this.

One thing that doesn't make any sense is a solar sail using an orange chip. it's just a solar sail. Candle firing structures are already expensive.

That's without commenting on the huge production chain needed for 1 orange chip, throwing them in solar sails doesn't seem balanced to me, the sail must be more accessible and cheaper, as Dysons projects that need millions of candles. its energy return is not so worth it, you do it today just to get photons, because it is not necessary. energy you get from the new containers you made.

If you can explain or balance this better I would appreciate it.

**Comment by Awbugl** [comment]
we have deliberately raised the difficulty of obtaining materials for the game - because origin version is just too easy.

btw, solar sails need a processor because they need to have an attitude control core - a processor couldn't be more appropriate.
I think you haven't unlocked Mega Buildings yet - they're powerful enough to produce a lot of items.
also, efficient recipe of processor might help too.

the part about generating photon - yes, that's what they are made for. Expensive, but worth it.
they are certainly not as efficient as fusion when generating energy - because the fusion materials in the game are so easily to get.
